language: android

jdk:
    - oraclejdk8

env:
    global:
        - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
    components:
        - tools
        - android-28
        - build-tools-28.0.3
        - extra-google-m2repository
        - extra-android-m2repository

sudo: false

script: ./gradlew test --stacktrace

notifications:
    email: false

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

